//
// Created by taxue on 2023/1/11.
//

#ifndef FIRETOOL_PID_DRIVER_ESP_FIRETOOL_PID_ADAPTOR_H
#define FIRETOOL_PID_DRIVER_ESP_FIRETOOL_PID_ADAPTOR_H

#endif //FIRETOOL_PID_DRIVER_ESP_FIRETOOL_PID_ADAPTOR_H
